### PR TITLE
fix: auth

### PR DESCRIPTION
**Pull request by daffafaizan**
## Brief Description

This fix is intended to decompose the user model and services and relocate business logic from the endpoint functions. I've created new **auth** files dedicated to authorization logic. Notable changes I've made are as follows:

1. Relocated **token generation and validation** from ```src.models.users``` to a dedicated service for auth ```src.services.auth```
2. Relocated and renamed **user login and register schemas** from ```src.schemas.users``` to ```src.schemas.auth```
3. Relocated **login** and **register** business logic from ```main.py``` to ```src.services.auth```
4. Set cookies on login

### Front end

On the front-end (Next.js using TypeScript), you can decompose the login response and store the tokens in variables or as a JSON object. For example, if you store the tokens in a JSON object called **auth** and you want to set is as a cookie, it can be done using the **js-cookie** dependency with the code:
```
Cookies.set("auth", JSON.stringify(auth), { expires: cookieExpiration });
```
assuming you have also set an expiration, example below:
```
const cookieExpiration = new Date(
      new Date().getTime() + refreshTokenExpirationTime,
    );
```

### Back end

On the back end, you can access the cookies by getting **request** (with the datatype **Request** from **FastAPI**) as a parameter to your endpoint function, and access the cookies. Example provided below:
```
from fastapi import Request

@app.get("/cookies")
def get_cookie(request: Request):
      access_token = request.cookies.get("access_token")
```

### CODE REVIEW

**Comment by annavaws** [comment]
I read your pull request description and the code you've changed. Nothing looks out of the ordinary. Although, It might be better to also describe how to use and utilize the cookies.

**Comment by daffafaizan** [comment]
> I read your pull request description and the code you've changed. Nothing looks out of the ordinary. Although, It might be better to also describe how to use and utilize the cookies.

I think an explanation on how to use the cookies depends on the front-end; which is not the scope of this pull request. I'll add comments later on if a description is needed.

**Comment by daffafaizan** [comment]
> > I read your pull request description and the code you've changed. Nothing looks out of the ordinary. Although, It might be better to also describe how to use and utilize the cookies.
> 
> I think an explanation on how to use the cookies depends on the front-end; which is not the scope of this pull request. I'll add comments later on if a description is needed.

Decided to add the description.

**Review by annavaws — APPROVED** [review]
Alright, all good now. Should be safe to proceed with the merge

**Pull request merged**
