### PR TITLE
feat: added new workflow for sonarqube code analysis

### PR DESCRIPTION
**Pull request by daffafaizan**
## Description

Merging this branch that introduces SonarQube to automatically review and analyze code for our repository.

**Benefits**:

1. Improved code quality through early detection of bugs, potential security vulnerabilities, and code smells.
2. Continuous monitoring of code metrics and trends.
3. Enhanced code maintainability and developer productivity.

### CODE REVIEW

**Comment by jeremyalv** [comment]
We should also enable this on push dev, other than that, it's all good

**Comment by jeremyalv** [comment]
We may need to add workflow ordering, if this script needs to run before dev-deployment
https://github.com/orgs/community/discussions/26271#discussioncomment-8258331

**Comment by daffafaizan** [comment]
> We may need to add workflow ordering in `dev-deployment`, if this script needs to run before `dev-deployment` https://github.com/orgs/community/discussions/26271#discussioncomment-8258331

Yes, however I don't think I'll need to implement that now. What do you think? Btw, I'll merge as soon as you approve.

**Review by annavaws — APPROVED** [review]
Yes, I think you can implement it later. In the meantime, I think it's better to merge it.

**Pull request merged**
